# Generated by Django 2.1.5 on 2019-03-13 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Post', 'Post')], default='Post', max_length=6)),
                ('content', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('is_image', models.BooleanField(default=False)),
                ('data_uri', models.TextField(blank=True)),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.IntegerField(choices=[(0, 'PUBLIC'), (1, 'PRIVATE'), (2, 'ONLY FRIENDS'), (3, 'FRIEND OF A FRIEND'), (4, 'SERVER ONLY'), (5, 'ONLY ME')], default=0)),
                ('unlisted', models.BooleanField(default=False)),
                ('accessible_users', models.ManyToManyField(blank=True, related_name='accessible_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
