# Generated by Django 2.1.5 on 2019-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190406_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accessible_users',
            field=models.TextField(default=False),
        ),
    ]
