# Generated by Django 2.1.5 on 2019-03-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesetting',
            name='require_auth',
        ),
        migrations.AddField(
            model_name='node',
            name='password',
            field=models.CharField(default='password', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(default='username', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_node',
            field=models.BooleanField(default=False, verbose_name='node'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
