# Generated by Django 2.1.5 on 2019-03-25 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20190325_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
