# Generated by Django 2.1.5 on 2019-02-19 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Post', 'Post')], default='Post', max_length=6)),
                ('content', models.TextField()),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.IntegerField(choices=[(0, 'Public'), (1, 'Only certain friends'), (2, 'Only friends'), (3, 'Friend of a friend'), (4, 'Server wide'), (5, 'Only me')], default=0)),
                ('unlisted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
