# Generated by Django 2.1.5 on 2019-02-19 18:25

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Post', 'Post')], default='Post', max_length=6)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.IntegerField(choices=[(0, 'Public'), (1, 'Only certain friends'), (2, 'Only friends'), (3, 'Friend of a friend'), (4, 'Server wide'), (5, 'Only me')], default=0)),
                ('unlisted', models.BooleanField(default=False)),
            ],
        ),
    ]
