# Generated by Django 2.1.5 on 2019-03-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[(0, 'application/base64'), (1, 'text/markdown'), (2, 'image/jpeg;base64'), (3, 'image/png;base64'), (4, 'text/plain')], default='text/plain', max_length=18),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'PUBLIC'), (1, 'PRIVATE'), (2, 'FRIENDS'), (3, 'FOAF'), (4, 'SERVERONLY'), (5, 'ONLY ME')], default=0),
        ),
    ]
