# Generated by Django 2.1.5 on 2019-02-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190216_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Only certain friends'), (2, 'Only friends'), (3, 'Friend of a friend'), (4, 'Server wide'), (5, 'Only me')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
