# Generated by Django 2.1.5 on 2019-03-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190311_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
