# Generated by Django 2.1.5 on 2019-02-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190217_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(6, 'Post')], default=6),
        ),
    ]
