# Generated by Django 2.1.5 on 2019-02-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Post', 'Post')], default='Post', max_length=5),
        ),
    ]
