# Generated by Django 2.1.5 on 2019-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190312_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_uri',
            field=models.TextField(blank=True),
        ),
    ]
