# Generated by Django 2.1.5 on 2019-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190217_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Post', 'Post')], default='Post', max_length=6),
        ),
    ]
