# Generated by Django 2.1.5 on 2019-03-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.TextField(default='hostname', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.TextField(default='theurl', max_length=500),
            preserve_default=False,
        ),
    ]
