# Generated by Django 2.1.5 on 2019-03-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190312_0008'),
        ('users', '0002_auto_20190310_0158'),
    ]

    operations = [
    ]
