# Generated by Django 2.1.5 on 2019-02-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_limit', models.IntegerField(default=10)),
                ('require_auth', models.BooleanField(default=True)),
            ],
        ),
    ]
