# Generated by Django 2.1.5 on 2019-02-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_nodesettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NodeSettings',
            new_name='NodeSetting',
        ),
    ]
