# Generated by Django 2.1.5 on 2019-02-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190213_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesetting',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=1),
        ),
    ]
