# Generated by Django 2.1.5 on 2019-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190213_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesetting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
