# Generated by Django 2.1.5 on 2019-02-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190213_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesetting',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
