# Generated by Django 2.1.5 on 2019-02-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190213_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesetting',
            name='share_imgs',
            field=models.BooleanField(default=True, help_text='Specify if images should be shared with other servers.'),
        ),
        migrations.AddField(
            model_name='nodesetting',
            name='share_posts',
            field=models.BooleanField(default=True, help_text='Specify if posts should be shared with other servers.'),
        ),
        migrations.AlterField(
            model_name='nodesetting',
            name='node_limit',
            field=models.IntegerField(default=10, help_text='The maximum number of servers that should be connected at one time.'),
        ),
        migrations.AlterField(
            model_name='nodesetting',
            name='require_auth',
            field=models.BooleanField(default=True, help_text='Specify if incoming server connections require authentication.'),
        ),
    ]
