# Generated by Django 2.1.5 on 2019-02-16 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190216_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
                ('user2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend_id',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user1_id', 'user2_id')},
        ),
    ]
