# Generated by Django 2.1.5 on 2019-02-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190216_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user1_id',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user2_id',
            new_name='user2',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user1', 'user2')},
        ),
    ]
