# Generated by Django 2.1.5 on 2019-02-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190216_2302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
