# Generated by Django 2.1.5 on 2019-03-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20190312_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.TextField(default='text/plain', max_length=13),
        ),
    ]
