# Generated by Django 2.1.5 on 2019-03-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20190311_0236'),
        ('comments', '0003_auto_20190313_0305'),
        ('comments', '0004_comment_contenttype'),
    ]

    operations = [
    ]
